{'src/app_*',	
	[debug_info,
	 warn_unused_vars,
	 warn_unused_imports, 
	 verbose,
	 {outdir, "ebin"},
	 {i,[
             "include" 
	    ]}
   ]
}.


{'src/date*',	
	[debug_info,
	 warn_unused_vars,
	 warn_unused_imports, 
	 verbose,
	 {outdir, "ebin"},
	 {i,[
             "include" 
	    ]}
   ]
}.

{'src/password*',	
	[debug_info,
	 warn_unused_vars,
	 warn_unused_imports, 
	 verbose,
	 {outdir, "ebin"},
	 {i,[
             "include" 
	    ]}
   ]
}.


{'src/spark_*',	
	[debug_info,
	 warn_unused_vars,
	 warn_unused_imports, 
	 verbose,
	 {outdir, "ebin"},
	 {i,[
             "include" 
	    ]},
	 {i,[
             "../ejabberd-dev/trunk/include" 
	    ]},	    
	 {i,[
             "../deps" 
	    ]},
	 {i,[
             ".." 
	    ]}
   ]
}.


{'src/mod_spark_rabbitmq*',	
	[debug_info,
	 warn_unused_vars,
	 warn_unused_imports, 
	 verbose,
	 {outdir, "ebin"},
	 {i,[
             "include" 
	    ]},
	 {i,[
             "../deps" 
	    ]},
	 {i,[
             "../ejabberd-dev/trunk/include" 
	    ]},
	 {i,[
             ".." 
	    ]}
   ]
}.



{'src/xmerl_*',	
	[debug_info,
	 warn_unused_vars,
	 warn_unused_imports, 
	 verbose,
	 {outdir, "ebin"},
	 {i,[
             "include" 
	    ]}
   ]
}.



{'src/rabbit*',	
	[debug_info,
	 warn_unused_vars,
	 warn_unused_imports, 
	 verbose,
	 {outdir, "ebin"},
	 {i,[
             "include" 
	    ]},

     {i,[
             ".." 
	    ]}
   ]
}.

{'src/chat_message_model*',	
	[debug_info,
	 warn_unused_vars,
	 warn_unused_imports, 
	 verbose,
	 {outdir, "ebin"},
	 {i,[
             ".." 
	    ]},
	 {i,[
             "include" 
	    ]},
         {i, [
	     "../json_rec/include"
	    ]},
	 {i,[
             "../deps" 
	    ]},
	 {i, [
	     "../json_rec/deps/parse_trans/include"
	    ]}
   ]
}.

{'src/mongrel*',	
	[debug_info,
	 warn_unused_vars,
	 warn_unused_imports, 
	 verbose,
	 {outdir, "ebin"},
	 {i,[
             "include" 
	    ]}
   ]
}.

{'src/mod_spark_log_chat*',	
	[debug_info,
	 warn_unused_vars,
	 warn_unused_imports, 
	 verbose,
	 {outdir, "ebin"},
	 {i,[
             ".." 
	    ]},
	 {i,[
             "include" 
	    ]},

	 {i,[
             "../ejabberd-dev/trunk/include" 
	    ]},
	 {i,[
             "../deps" 
	    ]},
	 {i, [
	     "../json_rec"
	    ]},
	 {i, [
	     "../json_rec/deps"
	    ]}
   ]
}.


{'src/gen_*',	
	[debug_info,
	 warn_unused_vars,
	 warn_unused_imports, 
	 verbose,
	 {outdir, "ebin"},
	 {i,[
             "include" 
	    ]},
	 {i,[
             "../deps" 
	    ]},
	 {i,[
             ".." 
	    ]}
   ]
}.

