{'src/mod_spark_log_chat*',	
	[debug_info,
	 warn_unused_vars,
	 warn_unused_imports, 
	 verbose,
	 {outdir, "ebin"},
	 {i,[
             ".." 
	    ]},
	 {i,[
             "include" 
	    ]},

	 {i,[
             "../ejabberd-dev/trunk/include" 
	    ]},
	 {i,[
             "../deps" 
	    ]}
   ]
}.

